pages/course/[courseId]/index.tsx
Added code in [course]/index.tsx for proper display of the chapters, that should be visibile.
=> Display created chapters in details

.husky/pre-commit, package.json, pages/course/[courseId]/edit.tsx, pages/course/[courseId]/index.tsx, pnpm-lock.yaml
See #33
Improve error handling of various pages/components.
- Fixed JS error when navigating to course details page with invalid `courseId`
- Implement error state of form fields
- Display errors from GraphQL mutations
=> Improve error handling

package.json, pages/course/[courseId]/edit.tsx, src/schema.graphql
add fields for suggested start + end dates on chapter create + edit
=> Suggested start end

components/Navbar.tsx, pages/course/[courseId]/index.tsx, pages/course/create.tsx, pages/index.tsx, pages/join.tsx
Updated a few lines in the Navbar, index.tsx, join.tsx, course/create.tsx and course/id/index.tsx, to add more responsivness. In the home screen, the progress bars are being resized if the screen width hits certain breakpoints. 
Navbar course items might need a rework, meaning if the screen width falls under a certain breakpoint, secondary node might have to be displayed. Propably an abbreviation of the course name, but has to be discussed. 
Breakpoints are moistly the predefined ones from TailwindCSS and MUI.
=> Responsivness

components/Navbar.tsx
Reworked the Navbar to be similar to the designs of Marcel. Omitted the button in the navbar to switch sights. Had to alter highlight design, beause I could not figure out how to implement the originial design choice.
=> Navbar rework

app/student/course/[courseId]/page.tsx, components/RewardScores.tsx
Show real reward score from backend
Closes #54 
=> Show real reward scores from backend

components/RewardScores.tsx
=> Fix misaligned reward score bars

package.json, pnpm-lock.yaml
=> Fix pdfobject types dependency missing

app/courses/[courseId]/lecturer.tsx, app/courses/[courseId]/student.tsx
=> fixed chapter sorting to prevent reordering on update

components/MediaRecordSelector.tsx
Took the search field from "Join course".
=> added search field and moved file upload field

app/courses/[courseId]/flashcards/[flashcardSetId]/lecturer.tsx, app/courses/[courseId]/media/[mediaId]/lecturer.tsx, components/Content.tsx
deletion of flashcards and media on the content page, for invalid content it's directly besides the content
=> implement content deletion

components/MediaContentModal.tsx, components/MediaRecordSelector.tsx
=> Make content type overridable

.npmrc, app/courses/[courseId]/media/[mediaId]/lecturer.tsx, app/courses/[courseId]/media/[mediaId]/student.tsx, components/MediaContentModal.tsx, components/PdfViewer.tsx, next.config.js, package.json, pnpm-lock.yaml
- new pdf viewer to be able to track page views
- a pdf page counts as viewed after 5 seconds right now
- the user can mark sth as understood after 50% of video length or pdf pages has been viewed
- the user is nagged to mark it as understood after 80%
- also fixes the bug on media saving
=> Implement improved progress tracking

src/currentView.tsx
current pageview is saved to localStorage
=> save current view in local storage

app/courses/[courseId]/media/[mediaId]/lecturer.tsx, app/courses/[courseId]/media/[mediaId]/student.tsx, components/MediaContentModal.tsx, components/MediaRecordIcon.tsx, components/MediaRecordSelector.tsx, components/MediaRecordTypeSelector.tsx, package.json, src/schema.graphql
Use new mutations for creating a media contents and linking records.
Currently, that does not remove deselected records. The backend needs to update the mutation or provide a new one for this.
See #108 
=> Media new mutation

app/courses/[courseId]/lecturer.tsx, app/courses/[courseId]/student.tsx, components/ChapterHeader.tsx, components/SkillLevels.tsx
See #107 
I tried more sophisticated badges with different shapes and some metallic glint. They looked out of place, so I went with the hexagon and simple color.
I also tried to show the skill type permanently but I could not get it to look right, mostly because of the different label lengths. The tooltip worked out though.
Because of my initial plan of having different badges, I divided it into five blocks:
Level 0-19: Stone (not completely sure about this one)
Level 20-39: Bronze
Level 40-59: Silver
Level 50-79: Gold
Level 80-100: Emerald
As its simpler badges now, we could add more blocks easily (if desired).
In case of manual test, please document the test well including a set of user instructions and prerequisites. Each including an …
=> Redesign skill levels

components/Navbar.tsx
=> redirect back to login after logout

pnpm-lock.yaml, src/RelayEnvironment.ts
=> fix refreshes when token changes

app/(dashboard)/student.tsx
Added simple text + link, if no courses were joined. Picture shows link, if hovered over.
=> Empty dashboard

app/courses/[courseId]/student.tsx, components/Navbar.tsx, components/RewardScores.tsx
Edited the course page/Navbar, for compatibility with smaller screens
=> Small Screen responsivness

components/MediaRecordSelector.tsx
=> fetch only the current user's media records

app/courses/[courseId]/statistics/student.tsx
=> fetch id fields to prevent merging queries

app/courses/[courseId]/lecturer.tsx, app/courses/[courseId]/statistics/student.tsx, app/courses/[courseId]/student.tsx, mockserver/server.ts, src/schema.graphql
Rename all occurences of coursesById to coursesByIds (name of query was changed in the backend)
=> Rename coursesById to coursesByIds

app/courses/[courseId]/flashcards/[flashcardSetId]/lecturer.tsx, app/courses/[courseId]/flashcards/[flashcardSetId]/student.tsx, src/schema.graphql
Sollte jetzt wieder wie vorher funktionieren. Änderungen für Bilder und anders sollte in einem neuen Issue im nächsten Sprint passieren.
=> Api changes

app/(dashboard)/lecturer.tsx, app/courses/create/lecturer.tsx
=> implement adding multiple chapters at once

components/Content.tsx, src/schema.graphql
the backend doesn't return the correct data right now, for testing add `true || `
=> show a modal warning if no reward scores would be earned

app/courses/[courseId]/quiz/[quizId]/student.tsx, src/schema.graphql
=> implement quiz progress tracking

app/courses/[courseId]/student.tsx, components/AddChapterModal.tsx, components/EditChapterModal.tsx, components/dialogs/chapterDialog.ts
=> Chapter start validation

app/courses/[courseId]/scoreboard/page.tsx, components/Heading.tsx
Added a search bar in the scoreboard to search for your name.
=> added search textfield + search function

app/courses/[courseId]/lecturer.tsx
Optional contents were set as required and required contents as optional.
=> Fix optional/required mixup

app/(dashboard)/student.tsx, app/courses/[courseId]/flashcards/[flashcardSetId]/lecturer.tsx, app/courses/[courseId]/flashcards/[flashcardSetId]/student.tsx, app/courses/[courseId]/lecturer.tsx, app/courses/[courseId]/media/[mediaId]/lecturer.tsx, app/courses/[courseId]/media/[mediaId]/student.tsx, app/courses/[courseId]/quiz/[quizId]/lecturer.tsx, app/courses/[courseId]/quiz/[quizId]/student.tsx, app/courses/[courseId]/student.tsx, components/AddChapterModal.tsx, components/AddContentModal.tsx, components/AddFlashcardSetModal.tsx, components/AddStageButton.tsx, components/AssessmentMetadataFormSection.tsx, components/Content.tsx, components/DeleteStageButton.tsx, components/EditFlashcardSetModal.tsx, components/EditSectionButton.tsx, components/MediaContentModal.tsx, components/MediaRecordSelector.tsx, components/MultipleChoiceQuestionModal.tsx, components/RichTextEditor.tsx, relay.config.json, src/schema.graphql
=> adjust to backend changes

app/(dashboard)/student.tsx, app/courses/[courseId]/student.tsx, app/layout.tsx, components/ChapterHeader.tsx, components/Content.tsx, components/CourseCard.tsx, components/SkillLevels.tsx, components/Suggestion.tsx, pnpm-lock.yaml
=> More suggestions

app/courses/[courseId]/quiz/[quizId]/student.tsx, app/layout.tsx, components/AutosizeByText.tsx, components/RichTextEditor.tsx, components/quiz/ClozeQuestion.tsx, components/quiz/MultipleChoiceQuestion.tsx, components/quiz/QuestionDivider.tsx, package.json, pnpm-lock.yaml
Freetext blanks:
Drag-n-drop blanks:
The order of text/blank elements can change between reloads. Once the backend adds a position variable, this can be fixed easily.
Closes #174 
=> Cloze quiz student

app/courses/[courseId]/quiz/[quizId]/lecturer.tsx, app/courses/[courseId]/student.tsx, components/MultipleChoiceQuestionModal.tsx, components/RichTextEditor.tsx, components/quiz/AddClozeQuestionModal.tsx, components/quiz/AddQuestionButton.tsx, components/quiz/ClozeBlankFeedbackTooltip.tsx, components/quiz/ClozeQuestion.tsx, components/quiz/ClozeQuestionModal.tsx, components/quiz/ClozeQuestionPreview.tsx, components/quiz/DeleteQuestionButton.tsx, components/quiz/DeleteQuizButton.tsx, components/quiz/EditClozeQuestionButton.tsx, components/quiz/EditRichTextButton.tsx, components/quiz/MultipleChoiceQuestionPreview.tsx
Quiz lecturer view:
Edit cloze question:
Edit feedback:
Add new question:
Closes #162 
=> Cloze quiz lecturer

components/CourseCard.tsx
=> Change course card title style

components/quiz/AddClozeQuestionModal.tsx
Hint was not sent with mutation
=> Fix add hint when adding cloze question

docker-compose.yml
Updates the docker-compose file with arguments used by the local dev environment to correctly set up communication between frontend, backend & keycloak
=> update docker compose file with args for local dev env

app/courses/create/lecturer.tsx
When creating a new course, set it to published by default
=> set course to published by default

components/RichTextEditor.tsx, package.json, pnpm-lock.yaml
Handle rich text with media record ids that do not exist anymore.
Also works in the editor, so lecturers can delete it from the text.
=> Handle deleted media records in rich text

components/SkillLevels.tsx
=> hide skill levels when they cannot be achieved

app/courses/page.tsx, components/Navbar.tsx
=> Update course filters to hide unpublished courses for students

app/courses/[courseId]/flashcards/[flashcardSetId]/lecturer.tsx, app/courses/[courseId]/media/[mediaId]/lecturer.tsx, components/AddChapterModal.tsx, components/ChapterHeader.tsx, components/Content.tsx, components/DialogBase.tsx, components/EditChapterButton.tsx, components/quiz/DeleteQuizButton.tsx
=> Chapter bugfixes

app/courses/[courseId]/lecturer.tsx, app/courses/[courseId]/student.tsx, components/ChapterContent.tsx, components/ChapterHeader.tsx, components/OtherContent.tsx, src/schema.graphql
=> Implement contents without sections

app/courses/[courseId]/student.tsx, components/AddSectionButton.tsx, components/AddStageButton.tsx, components/ChapterHeader.tsx, components/CourseCard.tsx, components/LightTooltip.tsx, components/StudentChapter.tsx, components/StudentSection.tsx, components/StudentStage.tsx
Use chapter/course progress from backend
=> Backend course/chapter progress

components/ChapterHeader.tsx, components/SkillLevels.tsx
=> Add label to skill levels

components/AddFlashcardSetModal.tsx
=> Fix creating flashcards

app/courses/[courseId]/lecturer.tsx, app/courses/[courseId]/quiz/[quizId]/lecturer.tsx, app/courses/[courseId]/student.tsx, components/AddContentModal.tsx, components/AssessmentMetadataFormSection.tsx, components/ContentMetadataFormSection.tsx, components/DialogBase.tsx, components/EditCourseModal.tsx, components/Form.tsx, components/QuizModal.tsx, components/dialogs/chapterDialog.ts, components/quiz/MultipleChoiceQuestion.tsx, src/schema.graphql
=> Quiz flaschard bugs

app/courses/[courseId]/quiz/[quizId]/student.tsx, package.json, pnpm-lock.yaml
=> Fix confetti scrollbars

app/courses/[courseId]/flashcards/[flashcardSetId]/lecturer.tsx
=> Add autofill for flashcard label

components/quiz/AssociationQuestion.tsx, components/quiz/CorrectnessIndicator.tsx, components/quiz/MultipleChoiceQuestion.tsx
=> Display correct answers by backgroundColor, not checkbox color

app/courses/[courseId]/media/[mediaId]/student.tsx, components/MediaContentModal.tsx
closes #220
Tested visually, that I can mark a pdf as "Understood". -> Worked
Done it with another pdf, while network tab was open, to check that progress is sent to backend. -> worked
=> Remove 50% limit for marking as understood

app/courses/[courseId]/flashcards/[flashcardSetId]/student.tsx, components/StudentFlashcard.tsx, components/StudentFlashcardSide.tsx
Refactoring and fixing sides which are both question and answer.
Closes #264 
=> Refactor flashcards and fix missing answers

styles/globals.css, styles/preflight.css, tailwind.config.js
=> Fix tailwind / MUI css issues for buttons

components/AssessmentMetadataFormSection.tsx, components/EditFlashcardSetModal.tsx
=> Fix setting interval learning interval

app/(dashboard)/lecturer.tsx, components/Navbar.tsx, src/currentView.tsx, src/schema.graphql
=> Fix issue 265

app/courses/page.tsx, components/quiz/AddMultipleChoiceQuestionModal.tsx
add mutation for joining courses as student
=> add joinCourse mutation in page.tsx

app/(dashboard)/lecturer.tsx, app/(dashboard)/student.tsx, app/layout.tsx, components/Navbar.tsx, src/currentView.tsx
=> Hide switch-mode and start in correct mode

components/quiz/ClozeQuestionModal.tsx
=> Change wrong answer input

app/courses/page.tsx
Prevent joining courses that have not started yet or have already ended. This can cause issues, as the user does not have permissions to retrieve info from it.
=> Don't allow joining course outside their start/end

components/QuizModal.tsx, components/RichTextEditor.tsx, components/quiz/AssociationQuestionModal.tsx, components/quiz/ClozeQuestionModal.tsx, components/quiz/ClozeQuestionPreview.tsx, components/quiz/EditClozeQuestionButton.tsx, components/quiz/MutlipleChoiceQuestionModal.tsx
=> Quiz validation

app/courses/[courseId]/lecturer.tsx, app/courses/[courseId]/quiz/[quizId]/student.tsx, components/EditContentModal.tsx, components/RichTextEditor.tsx, components/content-link/InvalidContentLink.tsx, components/quiz/AddAssociationQuestionModal.tsx, components/quiz/AddClozeQuestionModal.tsx, components/quiz/AddMultipleChoiceQuestionModal.tsx, components/quiz/EditAssociationQuestionButton.tsx, components/quiz/EditClozeQuestionButton.tsx, components/quiz/EditMultipleChoiceQuestionButton.tsx
=> fix states not updating after mutations

app/courses/create/lecturer.tsx, components/AssessmentMetadataFormSection.tsx, components/EditCourseModal.tsx, components/quiz/ClozeQuestion.tsx, components/quiz/ClozeQuestionModal.tsx
=> mark all fields that are required as required

app/courses/[courseId]/media/[mediaId]/student.tsx, components/PdfViewer.tsx
adding limits for the size of pdfs and images.
closes #273
=> fix issue 280

app/(dashboard)/student.tsx
=> Grouping courses on the homepage

.github/workflows/testing.yaml, app/courses/[courseId]/lecturer.tsx, app/courses/[courseId]/members/lecturer.tsx, app/courses/[courseId]/members/loading.tsx, app/courses/[courseId]/members/page.tsx, components/DialogBase.tsx, components/Navbar.tsx, package.json, src/currentView.tsx, src/schema.graphql
=> Course members page

app/courses/[courseId]/flashcards/[flashcardSetId]/lecturer.tsx, components/flashcard/EditSideModal.tsx, components/flashcard/FlashcardSide.tsx, components/flashcard/LecturerEditFlashcard.tsx, components/flashcard/LocalFlashcard.tsx
=> Flashcard Lecturer refactoring

app/courses/[courseId]/flashcards/[flashcardSetId]/student.tsx, app/courses/[courseId]/flashcards/due/loading.tsx, app/courses/[courseId]/flashcards/due/page.tsx, app/courses/[courseId]/flashcards/due/student.tsx, app/courses/[courseId]/student.tsx, app/courses/page.tsx, components/RewardScoresHelpButton.tsx, components/StudentFlashcardSet.tsx
=> Due flashcards

src/currentView.tsx
=> Reset page view when logged in as student

app/courses/[courseId]/student.tsx, components/Navbar.tsx, src/schema.graphql
Fix bug with leave course and navbar
=> Leave course fix
